import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import BootstrapProvider from "./providers/BootstrapProvider";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BootstrapProvider>
          <Navbar />
          <main className="container py-5">{children}</main>
          <Footer />
        </BootstrapProvider>
      </body>
    </html>
  );
}